<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="306864" started-at="2018-01-22T10:14:21Z" finished-at="2018-01-22T10:19:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="306864" started-at="2018-01-22T10:14:21Z" finished-at="2018-01-22T10:19:28Z">
      <class name="com.wuliu.testcase.TestCase">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.wuliu.testcase.TestCase@7b49cea0]" name="beforeMethod" is-config="true" duration-ms="867" started-at="2018-01-22T18:14:21Z" finished-at="2018-01-22T18:14:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testCase()[pri:0, instance:com.wuliu.testcase.TestCase@7b49cea0]" name="testCase" duration-ms="305979" started-at="2018-01-22T18:14:22Z" finished-at="2018-01-22T18:19:28Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[执行出现异常，测试用例执行失败]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: 执行出现异常，测试用例执行失败
	at junit.framework.Assert.fail(Assert.java:47)
	at com.wuliu.keywords.AnalyzeExcelKeyWords.analyzeExcel(AnalyzeExcelKeyWords.java:59)
	at com.wuliu.testcase.TestCase.testCase(TestCase.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.wuliu.testcase.TestCase@7b49cea0]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-01-22T18:19:28Z" finished-at="2018-01-22T18:19:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.wuliu.testcase.TestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
